version: "3"

services:
  app:
    container_name: desafio-golang
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    